### ISSUE TITLE
Is it offline?

### ISSUE THREAD

**Issue by omonkulov** [alias-rahil/lyrics-searcher#1]
Today is July 23rd, 2021 and it seems that nothing is working. It can't find any lyrics.

**Comment by alias-rahil** [comment]
Seems to be working fine on my system, are you still facing the problem? Can you provide a little more detail? Is the CLI not working or the module?

**Comment by omonkulov** [comment]
Ye it is working fine now. But it was basically offline for 30 minutes on that day. Weird.

**Comment by alias-rahil** [comment]
Cool.

**Comment by alias-rahil** [comment]
Cool.
